base_path = '../'
__dataset_path__ = base_path + 'dataset/'
task_dataset_path = __dataset_path__ + 'tasks/'
index_dataset_path = __dataset_path__ + 'indexes/'
__output_path__ = base_path + 'output/'

eve_index_path = index_dataset_path + 'eve/'
word2vec_index_path = index_dataset_path + 'word2vec/'
fasttext_index_path = index_dataset_path + 'fasttext/'
glove_index_path = index_dataset_path + 'glove/'
